/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tobii_Tobii */

#ifndef _Included_tobii_Tobii
#define _Included_tobii_Tobii
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tobii_Tobii
 * Method:    jniInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tobii_Tobii_jniInit
  (JNIEnv *, jclass);

/*
 * Class:     tobii_Tobii
 * Method:    jniGazePosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_tobii_Tobii_jniGazePosition
  (JNIEnv *, jclass);

/*
 * Class:     tobii_Tobii
 * Method:    jniEyesPosition
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_tobii_Tobii_jniEyesPosition
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
